// Add this at the very bottom
apply plugin: 'com.google.gms.google-services'

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        println("Google Services JSON found")
    }
} catch(Exception e) {
    println("Google Services JSON not found - Appflow Native Config should provide this during build")
}